export enum iconTypes {
    AntDesign= "antDesign",
    Entypo="entypo",
    EvilIcons="evilicons",
    Feather="feather",
    FontAwesome5="fontAwesome5",
    Fontisto="fontisto",
    Foundation="foundation",
    Ionicons="ionicons",
    MaterialCommunityIcons="materialCommunityIcons",
    MaterialIcons="materialIcons",
    SimpleLineIcons="simpleLineIcons",
    Octicons="octicons",
    Zocial="zocial",
    FontAwesome="fontAwesome",
  };