enum RouteNames {
  // Tabs
  TAB_NAVIGATOR = 'TAB_NAVIGATOR',
  HOME_TAB = 'HOME_TAB',
  SETTINGS_TAB = 'SETTINGS_TAB',

  // Authentication
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  FORGET_PASSWORD_SCREEN = 'FORGET_PASSWORD',
  OTP_VERIFICATION_SCREEN = 'OTP_VERIFICATION',
  RESET_PASSWORD_SCREEN = 'RESET_PASSWORD',

  // PO
  PENDING_SCREEN = 'PENDING_SCREEN',
  DETAIL_PENDING_SCREEN = 'DETAIL_PENDING_SCREEN',
  HISTORY_SCREEN = 'HISTORY_SCREEN',
  // Home
  DASHBOARD_SCREEN = 'DASHBOARD_SCREEN',
  PO_DETAILS_CARD_SCREEN = 'PO_DETAILS_CARD_SCREEN',

  //DN
  ADD_DELIVERY_NOTE = 'ADD_DELIVERY_NOTE',
  PO_ADD_LIST_ITEM = 'PO_ADD_LIST_ITEM',

  //Invoice
  INVOICE_DETAILS_CARD_SCREEN = 'INVOICE_DETAILS_CARD_SCREEN',
  ADD_INVOICE = 'ADD_INVOICE',

  //Invoice
  INV_DETAILS_CARD_SCREEN = 'INV_DETAILS_CARD_SCREEN',

  // Settings
  SETTINGS_SCREEN = 'SETTINGS_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  CHANGE_PASSWORD_SCREEN = 'CHANGE_PASSWORD_SCREEN',
  CHANGE_LANGUAGE_SCREEN = 'CHANGE_LANGUAGE_SCREEN',
  PRIVACY_AND_POLICY_SCREEN = 'PRIVACY_AND_POLICY_SCREEN',

  //DN
  DN_DETAILS_CARD_SCREEN = 'DN_DETAILS_CARD_SCREEN',
  ABOUT_SCREEN = 'ABOUT_SCREEN',
}
export default RouteNames;
