#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "master" ]; then
  echo "You can't commit directly to master branch. Please create a new branch and raise MR to Master branch."
  exit 1
fi
echo "running pre-commit hook"
echo "pulling the master branch..."
git pull origin master
echo "running expo doctor checks"
npm run check
echo "running prettier fixes"
npm run prettier:fix
echo "running eslint fixes"
npm run lint:fix
